version: "3.3"

services:
    server:
        image: server:latest
        environment: 
            DARK_SKY_API: 
            LAT_LONG_CORDS: 
        build: ./backend
        ports:
            - 3030:3030
        volumes: 
            - /sys:/sys
    app:
        image: app:latest
        environment:
            SERVER_URL: http://server:3030
        build: ./frontend
        ports:
            - 5000:5000
        depends_on:
            - "server"
    